package com.gpcoder.entities;
// Generated Dec 29, 2019, 12:35:58 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "gp_user", catalog = "gp_hibernate_demo2")
public class User implements java.io.Serializable {

	private long id;
	private String email;
	private String password;

	public User() {
	}

	public User(long id) {
		this.id = id;
	}

	public User(long id, String email, String password) {
		this.id = id;
		this.email = email;
		this.password = password;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
}
